"""убрал nullable с description   в моделе  Product

Revision ID: dc4da9e833c4
Revises: ff4b98da34c3
Create Date: 2026-05-12 07:09:21.306795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4da9e833c4'
down_revision: Union[str, Sequence[str], None] = 'ff4b98da34c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###
