"""добавив релейшн шип для корзини та айтемін корзини 

Revision ID: fc00955e9e68
Revises: 378cd266b2c3
Create Date: 2026-05-18 11:06:35.144832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc00955e9e68'
down_revision: Union[str, Sequence[str], None] = '378cd266b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
